# Generated by Django 2.2.7 on 2019-11-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('treeId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TreeImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valId', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('leftRight', models.BooleanField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Tree')),
            ],
        ),
    ]
