# Generated by Django 2.2.7 on 2019-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeimplementation',
            name='leftRight',
        ),
        migrations.AddField(
            model_name='treeimplementation',
            name='leftId',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='treeimplementation',
            name='rightId',
            field=models.IntegerField(default=None),
        ),
    ]
