# Generated by Django 2.2.7 on 2019-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20191111_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeimplementation',
            name='id',
        ),
        migrations.AlterField(
            model_name='treeimplementation',
            name='valId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
