# Generated by Django 2.2.7 on 2019-11-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20191111_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeimplementation',
            name='parent_id',
            field=models.IntegerField(default=None),
        ),
    ]
